development:
  clients:
    default:
      database: sinamon_dev
      hosts:
        - 127.0.0.1:27017
  # options:
  #   raise_not_found_error: false
test:
  clients:
    default:
      database: sinamon_test
      hosts:
        - 127.0.0.1:27017
production:
  clients:
    default:
      database: sinamon
      hosts:
        - 127.0.0.1:27017