# http://documentcloud.github.io/jammit/

compress_assets: on #off

javascripts:
    deps:
        - app/scripts/vendor/underscore.js
        - app/scripts/vendor/backbone.js
    scripts:
        - app/scripts/plugins.js
        - app/scripts/main.js
        - app/scripts/models/*.js
        - app/scripts/collections/*.js
        - app/scripts/views/*.js
        - app/scripts/routes/*.js

stylesheets:
    styles:
        - public/css/main.css
