javascripts:
    deps:
        - app/scripts/vendor/underscore.js
        - app/scripts/vendor/backbone.js
    scripts:
        - app/scripts/plugins.js
        - app/scripts/main.js

stylesheets:
    styles:
        - public/css/main.css
