development:
  clients:
    default:
      database: sinamon
      hosts:
        - localhost:27017
  # options:
  #   raise_not_found_error: false
production:
  clients:
    default:
      database: sinamon
      hosts:
        - localhost:27017
